account:
    username: bot_username
    password: bot_password
    oauth:
        client_id: CLIENT_ID_HERE
        client_secret: CLIENT_SECRET_HERE
        redirect_uri: http://localhost/authorize_callback

bot:
    subreddit: botsubreddithere
    oauth_scopes:
        - edit
        - identity
        - read
        - history
        - submit
        - privatemessages
        - wikiedit
        - wikiread
    useragent:
        'default': Sample bot by /u/yournamehere v0.0 at /r/botsubreddithere
        'cleanup': Sample cleanup bot by /u/yournamehere v0.0 at /r/botsubreddithere
        'inbox': Sample inbox bot by /u/yournamehere v0.0 at /r/botsubreddithere
    footer: ^(Questions, comments, image suggestions? All are welcomed at /r/image_linker_bot)
    seen_len: 1000
    toomuch: |
        Message to send to people who reply-reply
    cleanup_time: 900  #Clean up every 15 minutes
    inbox_time: 900  #Check inbox every 15 minutes
    imagethread: thread_id # Thread to update with imagelist

    # Image extension handling
    extensions:
        - jpeg
        - jpg
        - png
        - gif
        - bmp
        - avi
        - tiff
        - tif
    animated_extensions:
        - gif
        - avi
    switchable_extensions:
        - jpeg
        - jpg
        - gif
        - png
    status_template: status_template.html

    # Ignore list functionality
    ignore_messages:
        - ignore me
    ignore_reply: You have been added to the ignore list
    unignore_messages:
        - unignore me
    unignore_reply: You have been removed from the ignore list

    #Database setup
    dbfile: joelbot.db
